<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="7" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-06T22:58:39 EDT" name="Suite" finished-at="2023-07-06T22:59:40 EDT" duration-ms="60883">
    <groups>
    </groups>
    <test started-at="2023-07-06T22:58:39 EDT" name="Test" finished-at="2023-07-06T22:59:40 EDT" duration-ms="60883">
      <class name="com.tn.qa.testcases.TN_LogInTest">
        <test-method is-config="true" signature="initialSetup()[pri:0, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:40 EDT" name="initialSetup" finished-at="2023-07-06T22:58:45 EDT" duration-ms="5913" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method signature="loginWithValidCredentials()[pri:1, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:45 EDT" name="loginWithValidCredentials" finished-at="2023-07-06T22:58:47 EDT" duration-ms="1709" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:47 EDT" name="tearDown" finished-at="2023-07-06T22:58:47 EDT" duration-ms="228" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initialSetup()[pri:0, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:47 EDT" name="initialSetup" finished-at="2023-07-06T22:58:52 EDT" duration-ms="4818" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method signature="loginWithInvalidCredentials()[pri:2, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:52 EDT" name="loginWithInvalidCredentials" finished-at="2023-07-06T22:58:53 EDT" duration-ms="1200" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tn.qa.testcases.TN_LogInTest.loginWithInvalidCredentials(TN_LogInTest.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:54 EDT" name="tearDown" finished-at="2023-07-06T22:58:54 EDT" duration-ms="189" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initialSetup()[pri:0, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:54 EDT" name="initialSetup" finished-at="2023-07-06T22:58:58 EDT" duration-ms="4436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method signature="loginWithNoCredential()[pri:3, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:58 EDT" name="loginWithNoCredential" finished-at="2023-07-06T22:58:59 EDT" duration-ms="1002" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at com.tn.qa.testcases.TN_LogInTest.loginWithNoCredential(TN_LogInTest.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:324)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:74)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:123)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithNoCredential -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tn.qa.testcases.TN_LogInTest@6f53b8a]" started-at="2023-07-06T22:58:59 EDT" name="tearDown" finished-at="2023-07-06T22:59:00 EDT" duration-ms="186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tn.qa.testcases.TN_LogInTest -->
      <class name="com.tn.qa.testcases.TN_SearchProduct">
        <test-method is-config="true" signature="initialSetup()[pri:0, instance:com.tn.qa.testcases.TN_SearchProduct@210ab13f]" started-at="2023-07-06T22:59:15 EDT" name="initialSetup" finished-at="2023-07-06T22:59:27 EDT" duration-ms="11684" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method signature="searchWithInvalidProduct()[pri:2, instance:com.tn.qa.testcases.TN_SearchProduct@210ab13f]" started-at="2023-07-06T22:59:27 EDT" name="searchWithInvalidProduct" finished-at="2023-07-06T22:59:28 EDT" duration-ms="764" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchWithInvalidProduct -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tn.qa.testcases.TN_SearchProduct@210ab13f]" started-at="2023-07-06T22:59:28 EDT" name="tearDown" finished-at="2023-07-06T22:59:28 EDT" duration-ms="247" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="initialSetup()[pri:0, instance:com.tn.qa.testcases.TN_SearchProduct@210ab13f]" started-at="2023-07-06T22:59:28 EDT" name="initialSetup" finished-at="2023-07-06T22:59:39 EDT" duration-ms="11556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method signature="verifySearchWithoutProduct()[pri:3, instance:com.tn.qa.testcases.TN_SearchProduct@210ab13f]" started-at="2023-07-06T22:59:39 EDT" name="verifySearchWithoutProduct" finished-at="2023-07-06T22:59:40 EDT" duration-ms="562" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySearchWithoutProduct -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tn.qa.testcases.TN_SearchProduct@210ab13f]" started-at="2023-07-06T22:59:40 EDT" name="tearDown" finished-at="2023-07-06T22:59:40 EDT" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tn.qa.testcases.TN_SearchProduct -->
      <class name="com.tn.qa.testcases.TN_Registration">
        <test-method is-config="true" signature="initialSetup()[pri:0, instance:com.tn.qa.testcases.TN_Registration@6f43c82]" started-at="2023-07-06T22:59:00 EDT" name="initialSetup" finished-at="2023-07-06T22:59:11 EDT" duration-ms="11820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialSetup -->
        <test-method signature="registerAccountWithExistingEmail()[pri:2, instance:com.tn.qa.testcases.TN_Registration@6f43c82]" started-at="2023-07-06T22:59:11 EDT" name="registerAccountWithExistingEmail" finished-at="2023-07-06T22:59:15 EDT" duration-ms="3373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerAccountWithExistingEmail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.tn.qa.testcases.TN_Registration@6f43c82]" started-at="2023-07-06T22:59:15 EDT" name="tearDown" finished-at="2023-07-06T22:59:15 EDT" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tn.qa.testcases.TN_Registration -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
